name: Build Python Container

on:
  push:
    branches:
      - main

  workflow_dispatch:
  
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:

      - name: Add Packer key
        run: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -

      - name: Add Packer repo
        run: sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

      - name: Install Packer
        run: sudo apt-get update && sudo apt-get install packer

      - name: Install Docker plugin for Packer
        run: sudo packer plugins install github.com/hashicorp/docker

      - uses: actions/checkout@v1

      - name: Create dotenv and add contents
        run: touch captchas4fun/.env && echo ${{ secrets.DOTENV_CONTENTS }} > captchas4fun/.env

      - name: Swap in Django secret
        run: sed -i 's/VerySecretPleaseChangeMeRoightNow/${{ secrets.DJANGO_SECRET }}/' captchas4fun/settings.py

      - name: Swap in allowed host
        run: sed -i 's/127\.0\.0\.1/${{ secrets.CAPTCHAS4FUN_HOST }}/' captchas4fun/settings.py
      
      - name: Packer build
        run: cd .build && packer build captchas4fun-python.pkr.hcl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
          